### ISSUE TITLE
Check for a reversible thrust electric engine

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/KAX#3]
[AFF](
https://forum.kerbalspaceprogram.com/index.php?/profile/116380-aff) asked about [adding reverse thrust to the Electric Engine](
https://forum.kerbalspaceprogram.com/index.php?/topic/180268-141-kerbal-aircraft-expansion-kaxl-%E2%80%94-under-new-management-%E2%80%94-v2800-2019-0110/&do=findComment&comment=3556697).

Blindly adding to the current engine can not be fair, such engine should be slightly heavier and slightly more expensive due the propeller's tilting mechanism. See [this](https://en.wikipedia.org/wiki/Thrust_reversal#Propeller-driven_aircraft) for the reasoning.

**Comment by Lisias** [comment]
Be sure to check this before working on the issue.

https://forum.kerbalspaceprogram.com/index.php?/topic/180268-141-kerbal-aircraft-expansion-kaxl-%E2%80%94-under-new-management-%E2%80%94-v2800-2019-0110/&do=findComment&comment=3558361

**Comment by theonegalen** [comment]
I think you're right about an engine that can reverse thrust in flight, but simply adding an option to mount the engine in the opposite direction, as a pusher, for example, would not necessitate the additional weight and cost.

**Comment by Lisias** [comment]
The reasoning from @theonegalen convinced me. I will add the reverse to the current engine.

**Comment by Lisias** [comment]
Hey!! As for KAX 2.8.0.2, the Electric Engines **HAS** reverse thrusters!

Closing this as I probably solved this one and forgot about...
